### PR TITLE
(Ready)[Up-to-date]Simplified Chinese Translation(Including the book)

### PR DESCRIPTION
**Pull request by lzyzl6**

### CODE REVIEW

**Comment by lzyzl6** [comment]
This translation is supposed to support older versions and most part of 1.1.2.
It means you can feel free to add it into different versions.

**Comment by lzyzl6** [comment]
I may translate the 1.1.2 later.
(and,have you ever thought of Crowdin?)

**Comment by lzyzl6** [comment]
OK，everything I can do now is done.(‾◡◝)
This translation **now** is ready for **1.1.2** and (should be good for) **previous** releases!!!

**Comment by UnlikePaladin** [comment]
Merged now! Big Thanks for the translation!

**Pull request merged**
