### PR TITLE
Want to offer Simplified Chinese translation(lncluding the book)

### PR DESCRIPTION
**Pull request by lzyzl6**
translation for 1.1.1
   ->zh_cn folder for the book
   ->and zh_cn.json for the general translation
I packed them into a .zip file
  
impressive(●'◡'●)creation!

### CODE REVIEW

**Comment by UnlikePaladin** [comment]
Thank you for the translation, I’ll review and merge it tomorrow!

**Comment by lzyzl6** [comment]
Sorry.I sent this PR a wrong one....

**Comment by lzyzl6** [comment]
[zh_cn.zip](https://github.com/UnlikePaladin/paladins-furniture/files/10330286/zh_cn.zip)

**Comment by lzyzl6** [comment]
Here is the translation.

**Comment by lzyzl6** [comment]
I  recreated this PR.Now you can simply merge them.

**Pull request closed without merging**
